# use base node image
FROM node:8.16.0-alpine

# Set working dir 
RUN mkdir /app
WORKDIR /app

# Add source
COPY real-time-chat-frontend/ /app


# Install dependencies
RUN yarn --pure-lockfile

# Start node server
CMD ["yarn", "start", "--verbose"]
